services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: Abastecimento
    environment:
      POSTGRES_DB: abastecimento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always